package com.example.meatshop.enums;

// enum for product category. Basically just meat/fish cuts.
public enum ProductCategory {
    // CHICKEN
    WHOLE_CHICKEN, CHICKEN_BREAST, CHICKEN_THIGH, CHICKEN_WING, CHICKEN_LEG, CHICKEN_CARCASS, MINCE_CHICKEN,
    // BEEF
    WHOLE_BEEF, BEEF_CHUCK, BEEF_RIB, BEEF_LOIN, BEEF_RUMP, BEEF_BRISKET, BEEF_SHORT_RIB, BEEF_SKIRT, BEEF_FLANK,
    BEEF_PLATE, BEEF_ROUND, BEEF_SHANK, BEEF_TAIL, BEEF_LIVER, BEEF_KIDNEY, BEEF_HEART, BEEF_BRAINS, BEEF_BONE_MARROW,
    BEEF_TENDON, MINCE_BEEF, OTHER_BEEF,
    // PORK
    WHOLE_PORK, PORK_HEAD, PORK_EAR, PORK_SHOULDER, PORK_NECK, PORK_LOIN, PORK_BELLY, PORK_HOCK, PORK_RIB,
    PORK_SPARE_RIB, PORK_BACK_RIB, PORK_TENDERLOIN, PORK_CHOP, PORK_FILLET, MINCE_PORK, OTHER_PORK,
    // LAMB
    WHOLE_LAMB, LAMB_CHUCK, LAMB_SHOULDER, LAMB_NECK, LAMB_LOIN, LAMB_BELLY, LAMB_HOCK, LAMB_RIB, LAMB_SPARE_RIB,
    LAMB_BACK_RIB, LAMB_TENDERLOIN, LAMB_CHOP, LAMB_FILLET, MINCE_LAMB, OTHER_LAMB,
    // DUCK
    WHOLE_DUCK, DUCK_BREAST, DUCK_LEG, DUCK_WING, DUCK_CARCASS, MINCE_DUCK, OTHER_DUCK,
    // FISH
    WHOLE_FISH, FISH_FILLET, FISH_STEAK, FISH_CARCASS, MINCE_FISH, OTHER_FISH,
    // OTHER
    OTHER
}
